### PR TITLE
Ensure example package doesn't try to publish

### PR DESCRIPTION
**Pull request by zephraph**
Simple solution to the deployment issue we were having earlier with the example package. 

Just mark it as private.

### CODE REVIEW

**Comment by zephraph** [comment]
I'm gonna mark this as a patch just to test what it does when it releases

**Comment by artsyit** [comment]
:rocket: PR was released in v1.2.0 :rocket:

**Comment by damassi** [comment]
Hmm - shouldn't this have bumped to 1.1.1?

**Comment by zephraph** [comment]
🤔

**Comment by zephraph** [comment]
Looking at the changelog that was generated, being as the last publish didn't fully succeed, it didn't actually process the PRs correctly. So this update was considered to have all of these changes: https://github.com/artsy/arc/commit/9f862f46953f78297462fb398d7e0ca9e0f5bb1e

**Pull request merged**
